language: node_js
node_js:
  - "5.3"
  - "4.2"
  - "0.12"
  - "iojs"
  - "node"
# addons:
#   code_climate:
#     repo_token: 
# after_script:
#   - npm run coverage
#   - codeclimate-test-reporter < coverage/lcov.info
